### ISSUE TITLE
Replace placeholders in a paragraph

### ISSUE THREAD

**Issue by HannesMatthias** [ruby-docx/docx#114]
Hello, is there a way to reliably replace a placeholder within a paragraph?

Sample paragraph: "Hello [FIRST_NAME] [LAST_NAME]. The meetings starts at [DATE]"

The code below doesn't work correctly, because the placeholders get cut off in the middle of a word sometimes.

For instance I get for each "text run" iteration:

Hello [FIRST_NAME] [LAST_                    # first iteration
NAME]. The meetings start at [DATE]" # second iteration

Therefore I cannot replace "[LAST_NAME]". 

```
doc.paragraphs.each do |p|
  p.each_text_run do |tr|
    tr.substitute('_placeholder_', 'replacement value')
  end
end
```

Thanks in advance

**Comment by WaKeMaTTa** [comment]
```ruby
doc.paragraphs.each do |p|
  p.each_text_run do |tr|
    tr.substitute('[LAST_NAME]', 'Matthias')
  end
end
```

**Comment by WaKeMaTTa** [comment]
mmm I didn't know that.

**Comment by HannesMatthias** [comment]
I just wonder, that nobody recognized it. Do you think, it will get fixed? Here is a word document to reproduce the error.

[reproduce.docx](https://github.com/ruby-docx/docx/files/6917287/reproduce.docx)

**Comment by satoryu** [comment]
@HannesMatthias I investigated the docx file you attached. 
As you may know, docx file is a zip file consists of XML files. one of the XML file is `word/document.xml`, which represents entire content. 

In this file, `[EMPLOYEE_LAST_NAME]` does not exist as it is split to two word `[EMPLOYEE_LAT_` and `NAME]`
```word/document.xml
      <w:r w:rsidR="00B53417">
        <w:rPr>
          <w:rFonts w:ascii="Univers" w:hAnsi="Univers"/>
          <w:sz w:val="24"/>
          <w:lang w:val="en-AU"/>
        </w:rPr>
        <w:t>[EMPLOYEE_LAST_</w:t>
      </w:r>
      <w:proofErr w:type="gramStart"/>
      <w:r w:rsidR="00B53417">
        <w:rPr>
          <w:rFonts w:ascii="Univers" w:hAnsi="Univers"/>
          <w:sz w:val="24"/>
          <w:lang w:val="en-AU"/>
        </w:rPr>
        <w:t>NAME]</w:t>
      </w:r>
```

This is editor's issue, MS Word and Google Docs sometimes split words internally but different from what we see. 

I recommend you to use bookmarks to point the place to where you want to insert some text , `Docx::Document#bookmarks` and `Docx::Elements::Bookmark#insert_text_after`. 

- [Add or delete bookmarks in a Word document or Outlook message - Office Support](https://support.microsoft.com/en-us/office/add-or-delete-bookmarks-in-a-word-document-or-outlook-message-f68d781f-0150-4583-a90e-a4009d99c2a0)

For example, if your docx file has a bookmark named 'last_name', you can insert some text `Jack` there by using the following code: 

```ruby
doc = Docx::Document.open('/path/to/your/word/file.docx')
bookmarks = doc.bookmarks

bookmark = bookmarks['last_name']
bookmark.insert_text_after('Jack')
```

but I didn't confirm this script would work as you expect.

**Comment by HannesMatthias** [comment]
Hello, thanks for the kind feedback. I will definitely try it out!
