### ISSUE TITLE
NameError: uninitialized constant Zip::File

### ISSUE THREAD

**Issue by parthnagori** [ruby-docx/docx#33]
when I try to read the doc by doing
doc = Docx::Document.open("tmp/document.docx")
I get an error saying "NameError: uninitialized constant Zip::File"
I have gem 'zip' & gem 'rubyzip' both in my gemfile. 
What can be the possible cause and solution for this?

**Comment by gedean** [comment]
Please, remove gem 'zip' from your gemfile, its outdated and out of use.
