### ISSUE TITLE
Zip::ZipError, I need help

### ISSUE THREAD

**Issue by apprentice1988** [ruby-docx/docx#5]
Hi
I installed docx gem in my project, and I tried open a docx file using Docx::Document.open("test.docx"). Then I got an error - "Zip::ZipError: zip end of central directory signature not found".  I knew it 's relative to my env, but I don't know how to solve this error. ps: I use ubuntu system.
Thx

**Comment by vkeziah** [comment]
I am facing the same issue , Can I have solution please

**Comment by chrahunt** [comment]
Hi @vkeziah,

The `open` method takes a file path and will not retrieve the content at a URL for you. You would have to download the document in a separate step (using a library like [`http`](https://github.com/httprb/http)) and then save the content locally using either a specific path you choose or the [`Tempfile`](http://ruby-doc.org/stdlib-2.4.0/libdoc/tempfile/rdoc/index.html)) standard library module. The path to this resource is what you would pass to `Docx::Document.open`.
