### ISSUE TITLE
Update the nokogiri dependency?

### ISSUE THREAD

**Issue by abartov** [ruby-docx/docx#71]
Hi!

There's a security vulnerability in **nokogiri** fixed in version 1.10.4.  This gem requires ~>1.8, holding back upgrades of nokogiri.  Could you release a version requiring the newer nokogiri, or just >1.8 open-endedly?  Thanks!

**Comment by mvz** [comment]
Hi @abartov, the specification `~> 1.8` already allows `1.10.4`, since it specifies the minor version number must be 8 or heigher.

**Comment by satoryu** [comment]
Updated the dependency 👍 
https://github.com/ruby-docx/docx/pull/72/commits/4628bbd64757112e17e06a1ea270835ae24951ae
