### ISSUE TITLE
Edit content from node

### ISSUE THREAD

**Issue by fercreek** [ruby-docx/docx#79]
There is some way to replace the content of inspect?
If I did something like this

```rb
d = Docx::Document.open('example.docx')

d.paragraphs.each do |p|
  p.node.inspect = p.node.inspect.gsub('Old text', 'Next text')
end
```

**Comment by misdoro** [comment]
@fercreek check out this one #75 
Beware, it was not yet released.

**Comment by fercreek** [comment]
Yeah! I tried that solution but I have a text with this format.
Hi, my name is ${user.full_name}, and when I use `each_text_run` the text is split like this
```
$
{
userfull_name
}
``` 

Do you have some suggestion? @misdoro

**Comment by misdoro** [comment]
Except updating your document to use exactly the same formatting for each part of `${userfull_name}`, not really. Each text run in a paragraph usually corresponds to a particular styling configuration.
You may also try importing/exporting to google docs to try to re-arrange formatting.

**Comment by pellibr** [comment]
hey @misdoro I'm using your replacing feature, but there's a problem with similar fields like this : 
_estado_, "Florida"
_estado_civil_, "Married"

it will replace like this: 
"Married" 
"Marriedcivil_"

I've tried some regex expressions on 'match' but coudn't figure it out 

Any idea? 

Best regards

**Comment by misdoro** [comment]
@pellibr you may try changing the order of keys in your hash to be from more specific to less specific, that should be a work-around.

Generally speaking it is not a good idea to use the same symbol as end/begin and space marker. Maybe replace surrounding _ by something else like [] or {}.

**Comment by pellibr** [comment]
@misdoro That's the best to avoid such problems, thanks
