### ISSUE TITLE
Not gettin docx class working properly on rails

### ISSUE THREAD

**Issue by pellibr** [ruby-docx/docx#87]
## Describe the bug

I'm trying to create a .docx template using rails but I'm getting problem in loading the 'docx' class. 

[Repository](https://github.com/pellibr/prc3)

```
NoMethodError in ClientsController#create
`undefined method `close' for nil:NilClass`
```
[Image](https://imgur.com/a/j6kopyE)

*Controller*
```
  def templater
    require "docx"
    doc = Docx::Document.open("base.docx")
      doc.paragraphs.each do |p|
        p.each_text_run do |tr|
          tr.substitute('_placeholder', 'teste')
        end
      end
      doc.save('base-edit.docx')
  end
```

*Gemfile*
`gem 'docx', :require => ["docx"]`

## Environment

- Ruby version: [e.g 2.6.5]
- `docx` gem version: generic gem docx (last version)
- OS: [e.g. Ubuntu]
- gem 'rails', '~> 5.2.4', '>= 5.2.4.1'

**Comment by WaKeMaTTa** [comment]
I made a Pull Request in your Rails repo: https://github.com/pellibr/prc3/pull/1

The problem is not in the gem. The problem is in our code. Check my Pul Request: https://github.com/pellibr/prc3/pull/1

**Comment by pellibr** [comment]
Hello! THanks a lot and sorry for bother with this question, will study more about rails and dealing with files. 

Best regards !

**Comment by Manshi19** [comment]
Can someone help me with this issue? i am facing the same and the pull request is not avaialable. @WaKeMaTTa @brpl20

**Comment by WaKeMaTTa** [comment]
@Manshi19 sorry, I don't remember my fix. Share your code.

**Comment by 85636682** [comment]
```
file_path = File.join(Rails.public_path, '/files/file-sample_1MB.docx')
    ExceptionTrack::Log.create(title: "file_path", body: "#{file_path}")
    content = File.read(file_path)
    doc = Docx::Document.open(content)
```

my code alway show this error，i changed some docx files until error
